---
title: "HPAStainR vs Single Cell Data"
author: "Tim Nieuwenhuis"
date: "8/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(HPAStainR)
```


### Load HPA data
```{r}

hpa_dat <- read.table("../normal_tissue.tsv", sep = '\t', header = TRUE, stringsAsFactors = F)
cancer_dat <- HPAStainR::HPA_data_downloader("cancer",save_file = F)
```



### Read in PanglaoDB
```{r read in pangloa data}
dat <- read.table("PanglaoDB_markers_27_Mar_2020.tsv", sep = "\t", header = T, stringsAsFactors = F)

#See data organization
head(dat)

#Remove mouse data, product description, and nickname column
dat <- dat %>% select(-ends_with("mouse"), -nicknames, -product.description) %>%
  #protein coding only and mouse exclusive
  filter(species != "Mm",gene.type == "protein-coding gene" | gene.type == "protein coding gene") %>%
  #Make data more easily jive with hpastainr such as lungs vs lung
  mutate(organ = ifelse(organ == "Lungs", "Lung", organ),
         organ = ifelse(organ == "Heart", "Heart Muscle", organ)) %>%
  #make comprable column to hpastainr
  mutate(stainr_col = paste0(toupper(organ), " ", tolower(cell.type)))



```

## The for loop that runs PanglaoDB through HPAStainR
```{r }

#Get a list of panglao cell types
groupings <- unique(dat$stainr_col)

#This is used if trouble shooting
#cell_type <- groupings[1]

#Initiate df that will be added to via the loop
final_df <- NULL
#Use this to catch dropped cell types without staining
no_stain <- NULL

#For loop through panglao cell types to run them through HPAStainR
for (cell_type in groupings) {
  
  #Subset out data to just cell type of interest
  sub_dat <- dat %>% filter(stainr_col == cell_type)
  #Pull out the list of genes
  genes <- sub_dat$official.gene.symbol
  #Run HPAStainR
  stain_result <- HPAStainR(gene_list = genes,hpa_dat = hpa_dat, cancer_analysis = "normal", csv_names = T)
  
  stain_result
  
  if (is.na(stain_result[1,2])) {
    no_stain <- c(no_stain, cell_type)
    next
  }
  
  #Make a filter to get top stainr result from a tissue
  stain_result  <- stain_result %>%
    mutate(tissue = str_sub(cell_type, start = 1, end = (str_locate(cell_type,"-"))[,1]  -2),
           stained_count = str_count(detected_proteins,",") + 1)
  
  #Top results of HPAStainR
  top_result <- stain_result$cell_type[1]
  top_stain <- stain_result$staining_score[1]
  top_pval <- stain_result$p_val[1]
  top_adj_pval <- stain_result$p_val_adj[1]

  ##Below code is used to match tissue types from panglao and HPA and then pull
  #the topped matched hit
  
  #normal
  sub_stain <- stain_result %>% filter(tissue == toupper(unique(sub_dat$organ)))
  
  
  if (is.na(unique(sub_dat$organ))) {
    sub_dat$organ <- ""
  }
  
  #GI tract
  if ("GI TRACT" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("COLON", "DUODENUM", "RECTUM", "SMALL INTESTINE"))
  }
  
  #Blood brain barrier
  if ("BRAIN" == toupper(unique(sub_dat$organ)) |
      "endothelial cells (blood brain barrier)" == tolower(unique(sub_dat$cell.type))) {
    #Brain
    sub_stain <- stain_result %>% filter(tissue %in% c("CAUDATE",
                                                       "CEREBELLUM",
                                                       "CEREBRAL CORTEX",
                                                       "CHOROID PLEXUS",
                                                       "DORSAL RAPHE",
                                                       "HIPPOCAMPUS",
                                                       "HYPOTHALAMUS",
                                                       "PITUITARY GLAND",
                                                       "SUBSTANTIA NIGRA"))
    }
  #Eye
      if ("EYE" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("RETINA"))
      }
  #Breast
   if ("MAMMARY GLAND" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("BREAST",
                                                       "LACTATING BREAST"))
    }
  
    #reproductive
   if ("REPRODUCTIVE" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("TESTIS",
                                                       "OVARY"))
   }
      #adrenal
   if ("ADRENAL GLANDS" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("ADRENAL GLAND"))
   }
  
        #throid
   if ("THYROID" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("THYROID GLAND"))
   }
  
          #ENDOTHELIAL
   if ("endothelial cells (aorta)" == tolower(unique(sub_dat$cell.type))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("COLON"))
    }
  
  
        #bone and blood
   if ("BONE" == toupper(unique(sub_dat$organ)) | "BLOOD" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("BONE MARROW"))
   }
  
     if ("OLFACTORY SYSTEM" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("NASOPHARYNX"))
     }
  
       if ("IMMUNE SYSTEM" == toupper(unique(sub_dat$organ))) {
    
    sub_stain <- stain_result %>% filter(tissue %in% c("BONE MARROW",
                                                       "THYMUS",
                                                       "LYMPH NODE",
                                                       "TONSIL"))
    }
  
  
   if ("CONNECTIVE TISSUE" == toupper(unique(sub_dat$organ))) {
    #Brain
    sub_stain <- stain_result %>% filter(tissue %in% c("ADIPOSE TISSUE",
                                                       "SOFT TISSUE"))
    }
  
  #Stores the top result from the correct tissue in an object
  top_tiss_result <- sub_stain$cell_type[1]
  top_tiss_stain <- sub_stain$staining_score[1]
  top_tiss_pval <- sub_stain$p_val[1]
  top_tiss_adj_pval <- sub_stain$p_val_adj[1]
  
  #Catches no found tissues
  if (nrow(sub_stain) == 0) {
    top_tiss_result <- "tissue not found"
  }
  
  #Number of proteins used
  proteins_used <- length(unique(sub_dat$official.gene.symbol))
  
  #The average N of proteins used for the top ten results (not all tissues are tested equally)
  top_10_avg_prot_tested <- mean(head(stain_result$number_of_proteins))
  
  #Make confidence score to account for low protein count not being taken into account
  
  conf_score <- ifelse(proteins_used > 50, 50, proteins_used) * 0.02 * top_stain
  
  #If there is not enough data to run a chi_square turn results into NA
  if (is.null(top_adj_pval)) {
    top_adj_pval =NA 
    top_tiss_adj_pval =NA
     top_pval =NA 
    top_tiss_pval =NA
  }
  
  #Make single row output dataframe to be bound to main dataframe
  temp_dat <- data.frame(cell_type,
                         conf_score,
                         proteins_used,
                         top_10_avg_prot_tested,
                         top_result, top_stain,
                         top_pval,
                         top_adj_pval,
                         top_tiss_result,
                         top_tiss_stain,
                         top_tiss_pval,
                         top_tiss_adj_pval,
                         stringsAsFactors = F)
  
  #Bind it
  final_df <- rbind(final_df, temp_dat)
}

head(final_df)
write.csv(final_df, "supplemental_table_4_final_df_output.csv", row.names = F)
```

## PanglaoDB Data summary
### Includes unused csv and supplemental figure 1
```{r}

#Comparing available cell types between Panglao and HPA
avail_hpa_tissue_cells = unique(stain_result$cell_type)
avail_pangloa_tissue_cells = unique(dat$stainr_col)

avail_hpa_tissue_cells <- c(avail_hpa_tissue_cells,
                            rep("", length(avail_pangloa_tissue_cells) - length(avail_hpa_tissue_cells)))

tissues_and_cells <- cbind(avail_hpa_tissue_cells, avail_pangloa_tissue_cells)

colnames(tissues_and_cells) <- c("Tissue - Cells in HPA", " Tissue - Cells in PanglaoDB")

write.csv(tissues_and_cells, "panglao_v_hpa_available_cell_types.csv", row.names = F)


#Make a histogram of how many marker genes there are per cell type
summ_dat <- dat %>% group_by(cell.type) %>% summarize(genes = n())


summary(summ_dat)

supp_fig_1 <- ggplot(summ_dat, aes(x=genes)) + 
                geom_histogram(color="black", fill="white") +
                xlab("Marker Genes Per Cell Type") + 
                labs(title ="PanglaoDB Markers per cell type",
                     subtitle =  paste("N = ", nrow(summ_dat))) +
                ylab("Count")

supp_fig_1
  
ggsave("supplemental_figure_4_pangloa_hist.png", width = 8, height = 7)

```

Supplemental Table 2-3 
```{r}
 ## Make new column combining cell type and tissue
    hpa_dat_2 <- hpa_dat %>%
        mutate(Tissue = gsub("[[:digit:]]+", "", Tissue),
               tissue_cell = paste0(toupper(str_trim(Tissue)),
                                    " - ",
                                    Cell.type))


low_filter_supp_2   <- hpa_dat_2 %>%
    select(Gene.name, tissue_cell, Reliability, Level) %>%
    mutate(stained = ifelse(Level %in% c("Not detected", "N/A"), 0, 1)) %>%
    group_by(Gene.name) %>% summarise(n(), stain_count = sum(stained)) %>%
    mutate(stained_per_test = stain_count/ `n()`, filter = "low" ) %>%
    rename(`Times tested` = `n()`,
           `Time stained` = stain_count,
           `Stained per tested Low` = stained_per_test)

low_filter_supp_2 <- low_filter_supp_2 %>%
  mutate(`Rare Low` = ifelse(`Stained per tested Low` <
                         quantile(low_filter_supp_2$`Stained per tested Low`, .25),
                       "yes", "no")) %>%
  select(Gene.name, `Stained per tested Low`, `Rare Low` ) %>%
  filter(`Stained per tested Low` != 0)


normal_filter_supp_2   <- hpa_dat_2 %>%
    select(Gene.name, tissue_cell, Reliability, Level) %>%
    filter(Reliability %in% c("Enhanced", "Supported", "Approved")) %>%
    mutate(stained = ifelse(Level %in% c("Not detected", "N/A"), 0, 1)) %>%
    group_by(Gene.name) %>% summarise(n(), stain_count = sum(stained)) %>%
    mutate(stained_per_test = stain_count/ `n()`, filter = "normal" ) %>%
    rename(`Times tested` = `n()`,
           `Time stained` = stain_count,
           `Stained per tested Normal` = stained_per_test)

normal_filter_supp_2 <- normal_filter_supp_2 %>%
  mutate(`Rare Normal` = ifelse(`Stained per tested Normal` <
                         quantile(normal_filter_supp_2$`Stained per tested Normal`, .25),
                       "yes", "no")) %>%
  select(Gene.name, `Stained per tested Normal`, `Rare Normal` )


high_filter_supp_2   <- hpa_dat_2 %>%
    select(Gene.name, tissue_cell, Reliability, Level) %>%
    filter(Reliability %in% c("Enhanced","Approved")) %>%
    mutate(stained = ifelse(Level %in% c("Not detected", "N/A"), 0, 1)) %>%
    group_by(Gene.name) %>% summarise(n(), stain_count = sum(stained)) %>%
    mutate(stained_per_test = stain_count/ `n()`, filter = "high" ) %>%
    rename(`Times tested` = `n()`,
           `Time stained` = stain_count,
           `Stained per tested High` = stained_per_test)

high_filter_supp_2 <- high_filter_supp_2 %>%
  mutate(`Rare High` = ifelse(`Stained per tested High` <
                         quantile(high_filter_supp_2$`Stained per tested High`, .25),
                       "yes", "no")) %>%
  select(Gene.name, `Stained per tested High`, `Rare High` )


supp_table_2 <- left_join(left_join(low_filter_supp_2, normal_filter_supp_2), high_filter_supp_2) %>%
  mutate_if(is.numeric, round, 3)


write.csv(supp_table_2, "supplemental_table_2_gene_rarity.csv", row.names = FALSE)
####Repeat for cancer
 
cancer_sub_table <- cancer_dat %>%
  select(Gene.name, Cancer, High, Medium, Low, Not.detected) %>%
  mutate(stained = High + Medium + Low, tested = stained + Not.detected) %>%
  group_by(Gene.name) %>%
  summarise(stained = sum(stained,na.rm = T),
              tested = sum(tested,na.rm = T)) %>%
  mutate(`Stained per Tested` = round(stained/tested, 3)) %>%
  filter(!is.nan(`Stained per Tested`)) 
  
cancer_sub_table <- cancer_sub_table %>%
  mutate(Rare = ifelse(`Stained per Tested` <
                         quantile(cancer_sub_table$`Stained per Tested`, .25),
                       "Yes", "No"))
write.csv(cancer_sub_table, "supplemental_table_3_cancer_gene_rarity.csv", row.names = FALSE)
```


## HPA Data Summary
### Includes Supplemental Figure 2-4 and Supplemental Table 4
```{r}


#Generate data to gain an understanding of the amount of proteins tested to the amount of proteins stained

#Clean the hpa data
hpa_dat_new <- hpa_dat %>% 
      mutate(Tissue = gsub('[[:digit:]]+', '', Tissue),
             tissue_cell = paste0(toupper(str_trim(Tissue))," - ", Cell.type)) %>%
      distinct()



#Generate a summary of hpa_summary
hpa_dat_sum <- hpa_dat_new %>% group_by(tissue_cell) %>%
  summarise(proteins = n(), detected = sum(!(Level %in% "Not detected")) ) %>%
  mutate(det_o_test = detected/proteins,
         amount_tested = ifelse(proteins <= 50, "less than or equal to 50", 
                          ifelse(proteins > 50 & proteins <= 700, "between 51-700",
                          ifelse(proteins > 700 & proteins <= 15000, "between 701-15,000",
                                   "greater than 15,000")))) %>%
    filter(tissue_cell != "N/A - N/A")


hpa_dat_sum$amount_tested <- factor(hpa_dat_sum$amount_tested,
                                    levels = c("less than or equal to 50",
                                               "between 51-700",
                                               "between 701-15,000",
                                               "greater than 15,000"))

stat_mode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

stat_mode(hpa_dat_sum$proteins)
summary(hpa_dat_sum$proteins)


supp_fig_2 <- ggplot(hpa_dat_sum, aes(x=(proteins))) + 
              geom_histogram(color="black", fill="white", bins=100) +
              xlab("Tested Proteins Per Cell Type") +
              labs( title ="Human Protein Atlas Count of Tested Proteins per Cell Type",
                    subtitle = paste("N = ", nrow(hpa_dat_sum),"; 100 bins")) +
              geom_vline(xintercept= c(50,700, 15000),
                         linetype = c("longdash"),
                         color = c("blue","red", "dark green"),
                         size = 1.2) +
              geom_segment(aes(x = c(5000),
                               xend = c(10000),
                               y = c(20),
                               yend = c(20)),
                           color = "blue",
                           linetype = c("longdash"),
                           size = 1.2) +
              geom_segment(aes(x = c(5000),
                               xend = c(10000),
                               y = c(30),
                               yend = c(30)),
                           color = "red",
                           linetype = c("longdash"), size = 1.2) +
              geom_segment(aes(x = c(5000),
                               xend = c(10000),
                               y = c(40),
                               yend = c(40)),
                           color = "dark green",
                           linetype = c("longdash"),
                           size = 1.2) +
              annotate(geom="text", #angle = 90, vjust = 1.3,
                       size = 5,  
                       x=c(7500, 7500, 7500), 
                       y=c(25, 35, 45), 
                       label=c("50 Protein Line", "700 Protein Line", "15,000 Protein Line")
                          #color="red"
                      
                       ) +
              ylab("Count")

supp_fig_2

ggsave("supplemental_figure_1_proteins_tested.png", width = 9, height = 6)

supp_fig_3 <- ggplot(hpa_dat_sum, aes(x=detected)) + 
              geom_histogram(aes(fill = amount_tested),color="black", bins=50) +
              xlab("Detected Proteins Per Cell Type") +
              labs(title="HPA detected proteins",
              subtitle =paste("N = ", nrow(hpa_dat_sum))) +
              ylab("Count") + 
              scale_fill_discrete(name="Number of Proteins Tested")

supp_fig_3

ggsave("supplemental_figure_2_proteins_detected.png", width = 9, height = 6)


supp_fig_4 <- ggplot(hpa_dat_sum, aes(x=det_o_test)) + 
              geom_histogram(aes(fill =amount_tested), color="black") +
              xlab("Detected/Tested Proteins Per Cell Type") +
              labs(title="HPA detected/tested proteins",
                   subtitle =paste("N = ", nrow(hpa_dat_sum))) +
              ylab("Count") + 
              scale_fill_discrete(name="Number of Proteins Tested") 

supp_fig_4

ggsave("supplemental_figure_3_proteins_detected_divby_tested.png", width = 9, height = 6)


hpa_dat_sum_out <- select(hpa_dat_sum,
                          `Cell Type` = tissue_cell,
                          `Tested Proteins` = proteins,
                          `Detected Proteins` = detected,
                          `Detected Tested Ratio` = det_o_test)

write.csv(hpa_dat_sum_out, "supplemental_table_1_hpa_cell_type_tested_ratio.csv",row.names = F)


pdf(file = "Supplemental_Figures.pdf", width = 9, height = 7)
supp_fig_2
supp_fig_3
supp_fig_4
supp_fig_1
dev.off()
```

Recapitulate McCall experiment, file
```{r}

file_path <- "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5011060/bin/mmc3.xls"

temp = tempfile(fileext = ".xlsx")
download.file(file_path, destfile=temp, mode='wb')

lung_clust <- readxl::read_xls(temp)

supp_table_4 <- HPAStainR(lung_clust$`Cluster A`, hpa_dat = hpa_dat, cancer_dat = cancer_dat)
supp_table_5 <- HPAStainR(lung_clust$`Cluster B`, hpa_dat = hpa_dat, cancer_dat = cancer_dat)


supp_table_4
supp_table_5

write.csv(supp_table_4, "supplemental_table_4_pneumocytes.csv",row.names = F)
write.csv(supp_table_5, "supplemental_table_5_bronchus.csv", row.names = F)
```

